# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.remote.webelement import WebElement

from selenium.webdriver.firefox.options import Options as FirefoxOptions

options = FirefoxOptions()
options.add_argument('--headless')
driver = webdriver.Firefox(executable_path=r'./geckodriver', options=options)

driver.get("http://www.ifsul.edu.br/")
driver.implicitly_wait(5)
driver.get_screenshot_as_file('./ifsul_website.png')
  
