'''
Task: 

Tendo como ponto de partida o endereço: https://www.bage.rs.gov.br

5. Salve uma captura da tela principal do portal com nome de "bage_portal.png".

Solution:
'''

# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.remote.webelement import WebElement

from selenium.webdriver.firefox.options import Options as FirefoxOptions

options = FirefoxOptions()
options.add_argument('--headless')
driver = webdriver.Firefox(executable_path=r'./geckodriver', options=options)

# ativa a execução em GUI mode
#driver = webdriver.Firefox()

driver.get("https://www.bage.rs.gov.br/")
driver.implicitly_wait(5)
driver.get_screenshot_as_file('./bage_portal.png')
driver.close()
  
